### PR TITLE
Fix Gitlab parsing for repo with `-`

### PR DESCRIPTION
**Pull request by boozec**
Hi all :wave: unfortunately the branch rename closed the old PR at https://github.com/nephila/giturlparse/pull/74

# Description

Gitlab URLs has the format with "/-/blob/". This PR fixs the parser editing the FORMAT string with the "/-/" before the ('blob'|'tree').

eg: The string "https://gitlab.com/gitlab-org/gitlab/blob/master/README.md" is valid as "https://gitlab.com/gitlab-org/gitlab/-/blob/master/README.md".

## References

Fixs https://github.com/nephila/giturlparse/issues/42

# Checklist

* [x] Code lint checked via `inv lint`
* [x] Tests added

### CODE REVIEW

**Comment by protoroto** [comment]
@boozec Thanks a lot! Will make  @yakky review the code!

**Comment by protoroto** [comment]
@boozec Sorry to bother, but after merging `master` branch into yours tests are broken: is there any chance you can have a look at it?

**Comment by boozec** [comment]
Hi @protoroto it was caused by a typo with a `~`. It should work again now :)

**Comment by protoroto** [comment]
> Hi @protoroto it was caused by a typo with a `~`. It should work again now :)

Thank you very much! I really hope we'll be able to merge this and release a new version as soon as possible!

**Review by yakky — APPROVED** [review]

**Pull request merged**
